from enum import StrEnum


class Role(StrEnum):
    CITIZEN = "CITIZEN"
    COLLECTION_WORKER = "COLLECTION_WORKER"
    MUNICIPAL_OFFICER = "MUNICIPAL_OFFICER"
    RECYCLER = "RECYCLER"
    SYSTEM_ADMIN = "SYSTEM_ADMIN"


class UserStatus(StrEnum):
    ACTIVE = "ACTIVE"
    DISABLED = "DISABLED"


class Availability(StrEnum):
    AVAILABLE = "AVAILABLE"
    UNAVAILABLE = "UNAVAILABLE"
    ON_ROUTE = "ON_ROUTE"


class PickupStatus(StrEnum):
    PENDING = "PENDING"
    SCHEDULED = "SCHEDULED"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    MISSED = "MISSED"


class PickupStopStatus(StrEnum):
    PENDING = "PENDING"
    COLLECTED = "COLLECTED"
    SKIPPED = "SKIPPED"
    DELAYED = "DELAYED"


class BulkRequestStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"


class DelayReason(StrEnum):
    VEHICLE_BREAKDOWN = "VEHICLE_BREAKDOWN"
    HEAVY_TRAFFIC = "HEAVY_TRAFFIC"
    ROAD_BLOCKED = "ROAD_BLOCKED"
    WEATHER = "WEATHER"
    WASTE_NOT_READY = "WASTE_NOT_READY"
    OTHER = "OTHER"


class WasteSeverity(StrEnum):
    ROUTINE = "ROUTINE"
    HAZARDOUS = "HAZARDOUS"


class BatchStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    CLAIMED = "CLAIMED"
    SCHEDULED = "SCHEDULED"
    COLLECTED = "COLLECTED"
    REJECTED = "REJECTED"
    PROCESSED = "PROCESSED"


class BatchQuality(StrEnum):
    CLEAN = "CLEAN"
    MOISTURE_AFFECTED = "MOISTURE_AFFECTED"
    MIXED = "MIXED"
    UNSAFE = "UNSAFE"


class CreditReason(StrEnum):
    PICKUP_RECYCLING = "PICKUP_RECYCLING"
    MANUAL_ADJUSTMENT = "MANUAL_ADJUSTMENT"


class CreditStatus(StrEnum):
    CONFIRMED = "CONFIRMED"
    REVERSED = "REVERSED"


class BadgeCategory(StrEnum):
    CONSISTENCY = "CONSISTENCY"
    VOLUME = "VOLUME"
    SPECIAL = "SPECIAL"


class TicketType(StrEnum):
    MISSED_PICKUP = "MISSED_PICKUP"
    OVERFLOW = "OVERFLOW"
    MIXED_WASTE = "MIXED_WASTE"
    DELAY = "DELAY"
    OTHER = "OTHER"


class TicketStatus(StrEnum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    REOPENED = "REOPENED"
    CLOSED = "CLOSED"


class ReuseCategory(StrEnum):
    FURNITURE = "FURNITURE"
    ELECTRONICS = "ELECTRONICS"
    CLOTHING = "CLOTHING"
    BOOKS = "BOOKS"
    HOUSEHOLD = "HOUSEHOLD"
    OTHER = "OTHER"


class ReuseCondition(StrEnum):
    GOOD = "GOOD"
    FAIR = "FAIR"


class ReuseStatus(StrEnum):
    PENDING_APPROVAL = "PENDING_APPROVAL"
    AVAILABLE = "AVAILABLE"
    CLAIM_PENDING = "CLAIM_PENDING"
    COMPLETED = "COMPLETED"
    REJECTED = "REJECTED"
    WITHDRAWN = "WITHDRAWN"


class ReuseClaimStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class ExportJobType(StrEnum):
    COMPLAINTS = "COMPLAINTS"
    CREDIT_LEDGER = "CREDIT_LEDGER"
    BATCHES = "BATCHES"
    INVENTORY = "INVENTORY"


class ExportJobStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class EntityType(StrEnum):
    PICKUP = "PICKUP"
    BATCH = "BATCH"
    CREDIT = "CREDIT"
    CREDIT_FACTOR = "CREDIT_FACTOR"
    REUSE_LISTING = "REUSE_LISTING"
    REUSE_CLAIM = "REUSE_CLAIM"
    BULK_REQUEST = "BULK_REQUEST"
    TICKET = "TICKET"


class TraceEventType(StrEnum):
    CREATED = "CREATED"
    STATUS_CHANGED = "STATUS_CHANGED"
    CREDIT_AWARDED = "CREDIT_AWARDED"
    CREDIT_REVERSED = "CREDIT_REVERSED"
    FACTOR_UPDATED = "FACTOR_UPDATED"
    BATCH_CLAIMED = "BATCH_CLAIMED"
    BATCH_COLLECTED = "BATCH_COLLECTED"
