"""add all models

Revision ID: 3e952e83f2b7
Revises: b37c64461ba8
Create Date: 2026-07-29 23:57:18.040921
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "3e952e83f2b7"
down_revision: str | None = "b37c64461ba8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "badges",
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column(
            "category",
            sa.Enum("CONSISTENCY", "VOLUME", "SPECIAL", name="badgecategory"),
            nullable=False,
        ),
        sa.Column("icon_key", sa.String(length=60), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("criteria", sa.Text(), nullable=False),
        sa.Column("threshold", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_badges")),
        sa.UniqueConstraint("code", name=op.f("uq_badges_code")),
    )
    op.create_table(
        "users",
        sa.Column("zone_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "CITIZEN",
                "COLLECTION_WORKER",
                "MUNICIPAL_OFFICER",
                "RECYCLER",
                "SYSTEM_ADMIN",
                name="role",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "DISABLED", name="userstatus"),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column("token_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("latitude", sa.Double(), nullable=True),
        sa.Column("longitude", sa.Double(), nullable=True),
        sa.Column(
            "availability",
            sa.Enum("AVAILABLE", "UNAVAILABLE", "ON_ROUTE", name="availability"),
            server_default="AVAILABLE",
            nullable=True,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["zone_id"], ["zones.id"], name="fk_users_zone_id_zones"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("phone", name=op.f("uq_users_phone")),
    )
    op.create_index("ix_users_role", "users", ["role"], unique=False)
    op.create_index("ix_users_status", "users", ["status"], unique=False)
    op.create_index("ix_users_zone_id", "users", ["zone_id"], unique=False)
    op.create_table(
        "waste_categories",
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("label", sa.String(length=60), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_waste_categories")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.Column(
            "actor_role",
            sa.Enum(
                "CITIZEN",
                "COLLECTION_WORKER",
                "MUNICIPAL_OFFICER",
                "RECYCLER",
                "SYSTEM_ADMIN",
                name="role",
            ),
            nullable=False,
        ),
        sa.Column("actor_name", sa.String(length=120), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("module", sa.String(length=40), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], name="fk_audit_logs_actor_id_users"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index("ix_audit_logs_actor_id", "audit_logs", ["actor_id"], unique=False)
    op.create_index(
        "ix_audit_logs_entity_type_id", "audit_logs", ["entity_type", "entity_id"], unique=False
    )
    op.create_table(
        "batches",
        sa.Column("ref_code", sa.String(length=20), nullable=False),
        sa.Column("collector_id", sa.UUID(), nullable=False),
        sa.Column("assigned_by_id", sa.UUID(), nullable=False),
        sa.Column("zone_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "AVAILABLE",
                "CLAIMED",
                "SCHEDULED",
                "COLLECTED",
                "REJECTED",
                "PROCESSED",
                name="batchstatus",
            ),
            server_default="AVAILABLE",
            nullable=False,
        ),
        sa.Column("waste_category", sa.String(length=20), nullable=False),
        sa.Column("declared_weight", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("final_weight", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column(
            "quality_status",
            sa.Enum("CLEAN", "MOISTURE_AFFECTED", "MIXED", "UNSAFE", name="batchquality"),
            server_default="CLEAN",
            nullable=False,
        ),
        sa.Column("contamination_note", sa.String(length=200), nullable=True),
        sa.Column("quality_set_by_id", sa.UUID(), nullable=True),
        sa.Column("destination_recycler_id", sa.UUID(), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processed_quantity", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("rejection_reason", sa.String(length=500), nullable=True),
        sa.Column("remarks", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quality_status != 'UNSAFE' OR (quality_status = 'UNSAFE' AND contamination_note IS NOT NULL AND length(btrim(contamination_note)) > 0)",
            name=op.f("ck_batches_contamination_note_mandatory_for_unsafe"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by_id"], ["users.id"], name="fk_batches_assigned_by_id_users"
        ),
        sa.ForeignKeyConstraint(
            ["collector_id"], ["users.id"], name="fk_batches_collector_id_users"
        ),
        sa.ForeignKeyConstraint(
            ["destination_recycler_id"],
            ["users.id"],
            name="fk_batches_destination_recycler_id_users",
        ),
        sa.ForeignKeyConstraint(
            ["quality_set_by_id"], ["users.id"], name="fk_batches_quality_set_by_id_users"
        ),
        sa.ForeignKeyConstraint(
            ["waste_category"],
            ["waste_categories.code"],
            name="fk_batches_waste_category_waste_categories",
        ),
        sa.ForeignKeyConstraint(["zone_id"], ["zones.id"], name="fk_batches_zone_id_zones"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_batches")),
        sa.UniqueConstraint("ref_code", name=op.f("uq_batches_ref_code")),
    )
    op.create_index(
        "ix_batches_destination_recycler_id", "batches", ["destination_recycler_id"], unique=False
    )
    op.create_index("ix_batches_status", "batches", ["status"], unique=False)
    op.create_index("ix_batches_waste_category", "batches", ["waste_category"], unique=False)
    op.create_table(
        "bulk_pickup_requests",
        sa.Column("requester_id", sa.UUID(), nullable=False),
        sa.Column("zone_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("requested_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approx_volume", sa.String(length=60), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "APPROVED", "REJECTED", "CANCELLED", "EXPIRED", name="bulkrequeststatus"
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("decided_by_id", sa.UUID(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category"],
            ["waste_categories.code"],
            name="fk_bulk_pickup_requests_category_waste_categories",
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_id"], ["users.id"], name="fk_bulk_pickup_requests_decided_by_id_users"
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"], ["users.id"], name="fk_bulk_pickup_requests_requester_id_users"
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"], ["zones.id"], name="fk_bulk_pickup_requests_zone_id_zones"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bulk_pickup_requests")),
    )
    op.create_index(
        "ix_bulk_pickup_requests_requester_id",
        "bulk_pickup_requests",
        ["requester_id"],
        unique=False,
    )
    op.create_index(
        "ix_bulk_pickup_requests_status", "bulk_pickup_requests", ["status"], unique=False
    )
    op.create_index(
        "ix_bulk_pickup_requests_zone_requested",
        "bulk_pickup_requests",
        ["zone_id", "requested_date"],
        unique=False,
    )
    op.create_table(
        "credit_factors",
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("credit_rate", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("co2_factor", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "credit_rate >= 0", name=op.f("ck_credit_factors_credit_rate_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["category"],
            ["waste_categories.code"],
            name="fk_credit_factors_category_waste_categories",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_factors")),
        sa.UniqueConstraint("category", name=op.f("uq_credit_factors_category")),
    )
    op.create_table(
        "daily_pickup_schedules",
        sa.Column("collector_id", sa.UUID(), nullable=False),
        sa.Column("zone_id", sa.UUID(), nullable=False),
        sa.Column("schedule_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_stops", sa.Integer(), server_default="0", nullable=False),
        sa.Column("completed_stops", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["collector_id"], ["users.id"], name="fk_daily_pickup_schedules_collector_id_users"
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"], ["zones.id"], name="fk_daily_pickup_schedules_zone_id_zones"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_pickup_schedules")),
    )
    op.create_index(
        "ix_daily_pickup_schedules_collector_id",
        "daily_pickup_schedules",
        ["collector_id"],
        unique=False,
    )
    op.create_index(
        "ix_daily_pickup_schedules_zone_id", "daily_pickup_schedules", ["zone_id"], unique=False
    )
    op.create_table(
        "export_jobs",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "job_type",
            sa.Enum("COMPLAINTS", "CREDIT_LEDGER", "BATCHES", "INVENTORY", name="exportjobtype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", name="exportjobstatus"),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_export_jobs_user_id_users"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_export_jobs")),
    )
    op.create_index("ix_export_jobs_user_id", "export_jobs", ["user_id"], unique=False)
    op.create_table(
        "inventory",
        sa.Column("zone_id", sa.UUID(), nullable=False),
        sa.Column("waste_category", sa.String(length=20), nullable=False),
        sa.Column(
            "current_weight", sa.Numeric(precision=12, scale=3), server_default="0", nullable=False
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["waste_category"],
            ["waste_categories.code"],
            name="fk_inventory_waste_category_waste_categories",
        ),
        sa.ForeignKeyConstraint(["zone_id"], ["zones.id"], name="fk_inventory_zone_id_zones"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory")),
        sa.UniqueConstraint("zone_id", "waste_category", name="uq_inventory_zone_category"),
    )
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("is_read", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_notifications_user_id_users"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        "ix_notifications_user_id_is_read", "notifications", ["user_id", "is_read"], unique=False
    )
    op.create_table(
        "reuse_listings",
        sa.Column("lister_id", sa.UUID(), nullable=False),
        sa.Column("zone_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_by_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=80), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "FURNITURE",
                "ELECTRONICS",
                "CLOTHING",
                "BOOKS",
                "HOUSEHOLD",
                "OTHER",
                name="reusecategory",
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("condition", sa.Enum("GOOD", "FAIR", name="reusecondition"), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING_APPROVAL",
                "AVAILABLE",
                "CLAIM_PENDING",
                "COMPLETED",
                "REJECTED",
                "WITHDRAWN",
                name="reusestatus",
            ),
            server_default="PENDING_APPROVAL",
            nullable=False,
        ),
        sa.Column("rejection_reason", sa.String(length=500), nullable=True),
        sa.Column("manager_notes", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status != 'REJECTED' OR (status = 'REJECTED' AND rejection_reason IS NOT NULL AND length(btrim(rejection_reason)) > 0)",
            name=op.f("ck_reuse_listings_rejection_reason_mandatory_for_rejected"),
        ),
        sa.ForeignKeyConstraint(
            ["lister_id"], ["users.id"], name="fk_reuse_listings_lister_id_users"
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"], ["users.id"], name="fk_reuse_listings_reviewed_by_id_users"
        ),
        sa.ForeignKeyConstraint(["zone_id"], ["zones.id"], name="fk_reuse_listings_zone_id_zones"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reuse_listings")),
    )
    op.create_index("ix_reuse_listings_status", "reuse_listings", ["status"], unique=False)
    op.create_index("ix_reuse_listings_zone_id", "reuse_listings", ["zone_id"], unique=False)
    op.create_table(
        "trace_events",
        sa.Column(
            "entity_type",
            sa.Enum(
                "PICKUP",
                "BATCH",
                "CREDIT",
                "CREDIT_FACTOR",
                "REUSE_LISTING",
                "REUSE_CLAIM",
                "BULK_REQUEST",
                "TICKET",
                name="entitytype",
            ),
            nullable=False,
        ),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "CREATED",
                "STATUS_CHANGED",
                "CREDIT_AWARDED",
                "CREDIT_REVERSED",
                "FACTOR_UPDATED",
                "BATCH_CLAIMED",
                "BATCH_COLLECTED",
                name="traceeventtype",
            ),
            nullable=False,
        ),
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=True),
        sa.Column("hash", sa.String(length=64), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], name="fk_trace_events_actor_id_users"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trace_events")),
        sa.UniqueConstraint("hash", name=op.f("uq_trace_events_hash")),
    )
    op.create_index(
        "ix_trace_events_entity_type_id", "trace_events", ["entity_type", "entity_id"], unique=False
    )
    op.create_table(
        "user_badges",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("badge_id", sa.UUID(), nullable=False),
        sa.Column(
            "earned_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(["badge_id"], ["badges.id"], name="fk_user_badges_badge_id_badges"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_user_badges_user_id_users"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_badges")),
        sa.UniqueConstraint("user_id", "badge_id", name="uq_user_badge"),
    )
    op.create_table(
        "pickups",
        sa.Column("ref_code", sa.String(length=20), nullable=False),
        sa.Column("resident_id", sa.UUID(), nullable=False),
        sa.Column("collector_id", sa.UUID(), nullable=True),
        sa.Column("zone_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("estimated_weight", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("actual_weight", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SCHEDULED",
                "ASSIGNED",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED",
                "MISSED",
                name="pickupstatus",
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("priority", sa.String(length=10), server_default="NORMAL", nullable=False),
        sa.Column("scheduled_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_slot", sa.String(length=30), nullable=True),
        sa.Column("is_contaminated", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("contamination_type", sa.String(length=40), nullable=True),
        sa.Column("contamination_cleared_by_id", sa.UUID(), nullable=True),
        sa.Column("contamination_cleared_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("credit_rate_applied", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("co2_factor_applied", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("batch_id", sa.UUID(), nullable=True),
        sa.Column(
            "co2_saved", sa.Numeric(precision=12, scale=3), server_default="0", nullable=False
        ),
        sa.Column(
            "credits_earned", sa.Numeric(precision=12, scale=2), server_default="0", nullable=False
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["batch_id"], ["batches.id"], name="fk_pickups_batch_id_batches"),
        sa.ForeignKeyConstraint(
            ["category"], ["waste_categories.code"], name="fk_pickups_category_waste_categories"
        ),
        sa.ForeignKeyConstraint(
            ["collector_id"], ["users.id"], name="fk_pickups_collector_id_users"
        ),
        sa.ForeignKeyConstraint(
            ["contamination_cleared_by_id"],
            ["users.id"],
            name="fk_pickups_contamination_cleared_by_id_users",
        ),
        sa.ForeignKeyConstraint(["resident_id"], ["users.id"], name="fk_pickups_resident_id_users"),
        sa.ForeignKeyConstraint(["zone_id"], ["zones.id"], name="fk_pickups_zone_id_zones"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pickups")),
        sa.UniqueConstraint("ref_code", name=op.f("uq_pickups_ref_code")),
    )
    op.create_index("ix_pickups_collector_id", "pickups", ["collector_id"], unique=False)
    op.create_index("ix_pickups_resident_id", "pickups", ["resident_id"], unique=False)
    op.create_index("ix_pickups_status", "pickups", ["status"], unique=False)
    op.create_index("ix_pickups_zone_id", "pickups", ["zone_id"], unique=False)
    op.create_table(
        "reuse_claims",
        sa.Column("listing_id", sa.UUID(), nullable=False),
        sa.Column("claimant_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", name="reuseclaimstatus"),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("decided_by_id", sa.UUID(), nullable=True),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status != 'REJECTED' OR (status = 'REJECTED' AND note IS NOT NULL AND length(btrim(note)) > 0)",
            name=op.f("ck_reuse_claims_claim_note_mandatory_for_rejected"),
        ),
        sa.ForeignKeyConstraint(
            ["claimant_id"], ["users.id"], name="fk_reuse_claims_claimant_id_users"
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_id"], ["users.id"], name="fk_reuse_claims_decided_by_id_users"
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"], ["reuse_listings.id"], name="fk_reuse_claims_listing_id_reuse_listings"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reuse_claims")),
    )
    op.create_index("ix_reuse_claims_claimant_id", "reuse_claims", ["claimant_id"], unique=False)
    op.create_index("ix_reuse_claims_listing_id", "reuse_claims", ["listing_id"], unique=False)
    op.create_table(
        "reuse_images",
        sa.Column("listing_id", sa.UUID(), nullable=False),
        sa.Column("img_url", sa.String(length=500), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"], ["reuse_listings.id"], name="fk_reuse_images_listing_id_reuse_listings"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reuse_images")),
    )
    op.create_index("ix_reuse_images_listing_id", "reuse_images", ["listing_id"], unique=False)
    op.create_table(
        "route_history",
        sa.Column("schedule_id", sa.UUID(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["daily_pickup_schedules.id"],
            name="fk_route_history_schedule_id_schedules",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_route_history")),
    )
    op.create_index("ix_route_history_schedule_id", "route_history", ["schedule_id"], unique=False)
    op.create_table(
        "credits",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("pickup_id", sa.UUID(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "co2_saved", sa.Numeric(precision=12, scale=3), server_default="0", nullable=False
        ),
        sa.Column(
            "reason",
            sa.Enum("PICKUP_RECYCLING", "MANUAL_ADJUSTMENT", name="creditreason"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("CONFIRMED", "REVERSED", name="creditstatus"),
            server_default="CONFIRMED",
            nullable=False,
        ),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["pickup_id"], ["pickups.id"], name="fk_credits_pickup_id_pickups"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_credits_user_id_users"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credits")),
        sa.UniqueConstraint("pickup_id", "reason", name="uq_credit_pickup_reason"),
    )
    op.create_index("ix_credits_user_id_status", "credits", ["user_id", "status"], unique=False)
    op.create_table(
        "daily_pickup_stops",
        sa.Column("pickup_id", sa.UUID(), nullable=False),
        sa.Column("schedule_id", sa.UUID(), nullable=False),
        sa.Column("resident_id", sa.UUID(), nullable=False),
        sa.Column("pickup_order", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "COLLECTED", "SKIPPED", "DELAYED", name="pickupstopstatus"),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("latitude", sa.Double(), nullable=True),
        sa.Column("longitude", sa.Double(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pickup_id"], ["pickups.id"], name="fk_daily_pickup_stops_pickup_id_pickups"
        ),
        sa.ForeignKeyConstraint(
            ["resident_id"], ["users.id"], name="fk_daily_pickup_stops_resident_id_users"
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["daily_pickup_schedules.id"],
            name="fk_daily_pickup_stops_schedule_id_daily_pickup_schedules",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_pickup_stops")),
    )
    op.create_index(
        "ix_daily_pickup_stops_resident_id", "daily_pickup_stops", ["resident_id"], unique=False
    )
    op.create_index(
        "ix_daily_pickup_stops_schedule_id", "daily_pickup_stops", ["schedule_id"], unique=False
    )
    op.create_table(
        "tickets",
        sa.Column("ref_code", sa.String(length=20), nullable=False),
        sa.Column("raised_by_id", sa.UUID(), nullable=False),
        sa.Column("pickup_id", sa.UUID(), nullable=True),
        sa.Column("zone_id", sa.UUID(), nullable=True),
        sa.Column(
            "issue_type",
            sa.Enum(
                "MISSED_PICKUP", "OVERFLOW", "MIXED_WASTE", "DELAY", "OTHER", name="tickettype"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("OPEN", "IN_PROGRESS", "RESOLVED", "REOPENED", "CLOSED", name="ticketstatus"),
            server_default="OPEN",
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.Column("resolved_by_id", sa.UUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["pickup_id"], ["pickups.id"], name="fk_tickets_pickup_id_pickups"),
        sa.ForeignKeyConstraint(
            ["raised_by_id"], ["users.id"], name="fk_tickets_raised_by_id_users"
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_id"], ["users.id"], name="fk_tickets_resolved_by_id_users"
        ),
        sa.ForeignKeyConstraint(["zone_id"], ["zones.id"], name="fk_tickets_zone_id_zones"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tickets")),
        sa.UniqueConstraint("ref_code", name=op.f("uq_tickets_ref_code")),
    )
    op.create_index("ix_tickets_raised_by_id", "tickets", ["raised_by_id"], unique=False)
    op.create_index("ix_tickets_status", "tickets", ["status"], unique=False)
    op.create_index("ix_tickets_zone_id", "tickets", ["zone_id"], unique=False)
    op.create_table(
        "delay_logs",
        sa.Column("stop_id", sa.UUID(), nullable=False),
        sa.Column("worker_id", sa.UUID(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "VEHICLE_BREAKDOWN",
                "HEAVY_TRAFFIC",
                "ROAD_BLOCKED",
                "WEATHER",
                "WASTE_NOT_READY",
                "OTHER",
                name="delayreason",
            ),
            nullable=False,
        ),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reason != 'OTHER' OR (reason = 'OTHER' AND note IS NOT NULL AND length(btrim(note)) > 0)",
            name=op.f("ck_delay_logs_delay_note_mandatory_for_other"),
        ),
        sa.ForeignKeyConstraint(
            ["stop_id"], ["daily_pickup_stops.id"], name="fk_delay_logs_stop_id_daily_pickup_stops"
        ),
        sa.ForeignKeyConstraint(["worker_id"], ["users.id"], name="fk_delay_logs_worker_id_users"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delay_logs")),
    )
    op.create_index("ix_delay_logs_stop_id", "delay_logs", ["stop_id"], unique=False)
    op.create_index("ix_delay_logs_worker_id", "delay_logs", ["worker_id"], unique=False)
    op.create_table(
        "mixed_waste_tags",
        sa.Column("stop_id", sa.UUID(), nullable=False),
        sa.Column("worker_id", sa.UUID(), nullable=False),
        sa.Column(
            "severity", sa.Enum("ROUTINE", "HAZARDOUS", name="wasteseverity"), nullable=False
        ),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["stop_id"],
            ["daily_pickup_stops.id"],
            name="fk_mixed_waste_tags_stop_id_daily_pickup_stops",
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"], ["users.id"], name="fk_mixed_waste_tags_worker_id_users"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mixed_waste_tags")),
    )
    op.create_index("ix_mixed_waste_tags_severity", "mixed_waste_tags", ["severity"], unique=False)
    op.create_index("ix_mixed_waste_tags_stop_id", "mixed_waste_tags", ["stop_id"], unique=False)
    op.add_column("zones", sa.Column("manager_id", sa.UUID(), nullable=True))
    op.create_foreign_key("fk_zones_manager_id_users", "zones", "users", ["manager_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_zones_manager_id_users", "zones", type_="foreignkey")
    op.drop_column("zones", "manager_id")
    op.drop_index("ix_mixed_waste_tags_stop_id", table_name="mixed_waste_tags")
    op.drop_index("ix_mixed_waste_tags_severity", table_name="mixed_waste_tags")
    op.drop_table("mixed_waste_tags")
    op.drop_index("ix_delay_logs_worker_id", table_name="delay_logs")
    op.drop_index("ix_delay_logs_stop_id", table_name="delay_logs")
    op.drop_table("delay_logs")
    op.drop_index("ix_tickets_zone_id", table_name="tickets")
    op.drop_index("ix_tickets_status", table_name="tickets")
    op.drop_index("ix_tickets_raised_by_id", table_name="tickets")
    op.drop_table("tickets")
    op.drop_index("ix_daily_pickup_stops_schedule_id", table_name="daily_pickup_stops")
    op.drop_index("ix_daily_pickup_stops_resident_id", table_name="daily_pickup_stops")
    op.drop_table("daily_pickup_stops")
    op.drop_index("ix_credits_user_id_status", table_name="credits")
    op.drop_table("credits")
    op.drop_index("ix_route_history_schedule_id", table_name="route_history")
    op.drop_table("route_history")
    op.drop_index("ix_reuse_images_listing_id", table_name="reuse_images")
    op.drop_table("reuse_images")
    op.drop_index("ix_reuse_claims_listing_id", table_name="reuse_claims")
    op.drop_index("ix_reuse_claims_claimant_id", table_name="reuse_claims")
    op.drop_table("reuse_claims")
    op.drop_index("ix_pickups_zone_id", table_name="pickups")
    op.drop_index("ix_pickups_status", table_name="pickups")
    op.drop_index("ix_pickups_resident_id", table_name="pickups")
    op.drop_index("ix_pickups_collector_id", table_name="pickups")
    op.drop_table("pickups")
    op.drop_table("user_badges")
    op.drop_index("ix_trace_events_entity_type_id", table_name="trace_events")
    op.drop_table("trace_events")
    op.drop_index("ix_reuse_listings_zone_id", table_name="reuse_listings")
    op.drop_index("ix_reuse_listings_status", table_name="reuse_listings")
    op.drop_table("reuse_listings")
    op.drop_index("ix_notifications_user_id_is_read", table_name="notifications")
    op.drop_table("notifications")
    op.drop_table("inventory")
    op.drop_index("ix_export_jobs_user_id", table_name="export_jobs")
    op.drop_table("export_jobs")
    op.drop_index("ix_daily_pickup_schedules_zone_id", table_name="daily_pickup_schedules")
    op.drop_index("ix_daily_pickup_schedules_collector_id", table_name="daily_pickup_schedules")
    op.drop_table("daily_pickup_schedules")
    op.drop_table("credit_factors")
    op.drop_index("ix_bulk_pickup_requests_zone_requested", table_name="bulk_pickup_requests")
    op.drop_index("ix_bulk_pickup_requests_status", table_name="bulk_pickup_requests")
    op.drop_index("ix_bulk_pickup_requests_requester_id", table_name="bulk_pickup_requests")
    op.drop_table("bulk_pickup_requests")
    op.drop_index("ix_batches_waste_category", table_name="batches")
    op.drop_index("ix_batches_status", table_name="batches")
    op.drop_index("ix_batches_destination_recycler_id", table_name="batches")
    op.drop_table("batches")
    op.drop_index("ix_audit_logs_entity_type_id", table_name="audit_logs")
    op.drop_index("ix_audit_logs_actor_id", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("waste_categories")
    op.drop_index("ix_users_zone_id", table_name="users")
    op.drop_index("ix_users_status", table_name="users")
    op.drop_index("ix_users_role", table_name="users")
    op.drop_table("users")
    op.drop_table("badges")
    # Clean up custom PostgreSQL enum types
    for enum_name in [
        "badgecategory",
        "role",
        "userstatus",
        "availability",
        "pickupstatus",
        "pickupstopstatus",
        "bulkrequeststatus",
        "delayreason",
        "wasteseverity",
        "batchstatus",
        "batchquality",
        "creditreason",
        "creditstatus",
        "tickettype",
        "ticketstatus",
        "reusecategory",
        "reusecondition",
        "reusestatus",
        "reuseclaimstatus",
        "exportjobtype",
        "exportjobstatus",
        "entitytype",
        "traceeventtype",
    ]:
        op.execute(f"DROP TYPE IF EXISTS {enum_name} CASCADE")
    # ### end Alembic commands ###
