"""check audit_logs foreign key

Revision ID: 850d4848124e
Revises: f127488ab2e4
Create Date: 2026-07-30 20:34:15.897149
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "850d4848124e"
down_revision: str | None = "f127488ab2e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
