"""add audit_logs table

Revision ID: f127488ab2e4
Revises: 3e952e83f2b7
Create Date: 2026-07-30 16:13:59.693755
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "f127488ab2e4"
down_revision: str | None = "3e952e83f2b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
